<a href="https://colab.research.google.com/github/sreeyadora/college/blob/main/LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Creating a simple matrix using NumPy Library**

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1],
              [3],
              [7],
              [2]])
print("a =\n", a)

A = np.array([[1, 3, 7, 2],
[5, 8, -9, 0],
[6, -7, 11, 12]])
print("\nA =\n", A)

a =
 [[1]
 [3]
 [7]
 [2]]

A =
 [[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]


### **Matrix Addition, Subtraction, Multiplication**

In [ ]:
A = np.matrix([[0, 1],
              [-2, -3]])
B = np.matrix([[1, 0],
              [3, -2]])
C = A + B
print("A+B =\n", C)

C = A - B
print("\nA-B =\n", C)

C = A * B
print("\nA*B =\n", C)# Not Working!, only elementwise Multiplication!

#Working Alternative 1
C = A.dot(B)
print("\nA*B =\n", C)

#Working Alternative 2
C = np.dot(A,B)
print("\nA*B =\n", C)

#Working Alternative 3
C = np.mat(A) * np.mat(B)
print("\nA*B =\n", C)

#Working Alternative 4
C = np.matmul(A,B)
print("\nA*B =\n", C)


A+B =
 [[ 1  1]
 [ 1 -5]]

A-B =
 [[-1  1]
 [-5 -1]]

A*B =
 [[  3  -2]
 [-11   6]]

A*B =
 [[  3  -2]
 [-11   6]]

A*B =
 [[  3  -2]
 [-11   6]]

A*B =
 [[  3  -2]
 [-11   6]]

A*B =
 [[  3  -2]
 [-11   6]]


### **Matrix Multiplication**

In [ ]:
A = np.array([[1, 5, 3],
              [4, 6, 6],
              [3, 8, 9]])

B = np.array([[1, 5, 3, 4],
              [4, 5, 7, 8],
              [7, 8, 9, 3]])

C = np.array([[1],
              [4],
              [3]])

D = np.array([[1, 5, 3]])

M = np.matmul(A,B)
print("M=\n", M)
#M = np.matmul(B,A) # Not Working!

M = np.matmul(A,C)
print("\nM=\n", M)
#M = np.matmul(C,A) # Not Working!

M = np.matmul(C,D)
print("\nM=\n", M)

M = np.matmul(D,C)
print("\nM=\n", M)

M=
 [[ 42  54  65  53]
 [ 70  98 108  82]
 [ 98 127 146 103]]

M=
 [[30]
 [46]
 [62]]

M=
 [[ 1  5  3]
 [ 4 20 12]
 [ 3 15  9]]

M=
 [[30]]


### **Transpose of a Matrix**

In [ ]:
A = np.array([[1, 3, 7, 2],
              [5, 8, -9, 0],
              [6, -7, 11, 12]])
print("A=\n"); print(A)
Atr = np.transpose(A)
print("\nTranspose of A="); print(Atr)

B = np.array([[1, 5],
              [4, 5],
              [3, 2],
              [7, 8]])
print("\nB="); print(B)
Btr = np.transpose(B)
print("\nTranspose of B="); print(Btr)

A=

[[ 1  3  7  2]
 [ 5  8 -9  0]
 [ 6 -7 11 12]]

Transpose of A=
[[ 1  5  6]
 [ 3  8 -7]
 [ 7 -9 11]
 [ 2  0 12]]

B=
[[1 5]
 [4 5]
 [3 2]
 [7 8]]

Transpose of B=
[[1 4 3 7]
 [5 5 2 8]]


### **Determinant of a Matrix**

In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
              [3, 4]])
Adet = la.det(A)
print(Adet)

B = np.array([[-1, 3, 0],
              [2, 1, -5],
              [1, 4, -2]])
Bdet = la.det(B)
print(Bdet)

-2.0000000000000004
-21.00000000000001


### **Inverse Matrices**

In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
              [3, 4]])
Ainv = la.inv(A)
print("Inverse of A =\n",Adet)

B = np.array([[-1, 3, 0],
              [2, 1, -5],
              [1, 4, -2]])
Binv = la.inv(B)
print("\nInverse of B =\n",Binv)

Inverse of A =
 -2.0000000000000004

Inverse of B =
 [[-0.85714286 -0.28571429  0.71428571]
 [ 0.04761905 -0.0952381   0.23809524]
 [-0.33333333 -0.33333333  0.33333333]]


### **Eigenvalues**

In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[0, 1],
              [-2, -3]])
Aeig, v = la.eig(A)
print("Eigen value of A =",Aeig)

Eigen value of A = [-1. -2.]


### **Matrices Rules**
### **Proving 𝐴𝐵 ≠ 𝐵𝐴**

In [ ]:
import numpy as np
A = np.array([[0, 1],
              [-2, -3]])
B = np.array([[1, 0],
              [3, -2]])
C = np.array([[1, 1],
              [1, -5]])
print("AB Not Equal BA")
L = np.matmul(A,B)
print("L=");print(L)
R = np.matmul(B,A)
print("R=");print(R)

AB Not Equal BA
L=
[[  3  -2]
 [-11   6]]
R=
[[0 1]
 [4 9]]


### **Matrices Rules**
### **Proving 𝐴(𝐵𝐶) = (𝐴𝐵)𝐶**

In [ ]:
print("A(BC) = (AB)C")
L = np.matmul(A,np.matmul(B,C))
print("L=");print(L)
R = np.matmul(np.matmul(A,B),C)
print("R=");print(R)

A(BC) = (AB)C
L=
[[  1  13]
 [ -5 -41]]
R=
[[  1  13]
 [ -5 -41]]


### **Solving Linear Equations**

In [ ]:
import numpy as np
import numpy.linalg as la
A = np.array([[1, 2],
              [3, 4]])
b = np.array([[5],
              [6]])
Ainv = la.inv(A)
x = Ainv.dot(b)
print(x)

[[-4. ]
 [ 4.5]]


### **Solving Linear Equations**
### **We can also use the linalg.solve() function**

In [ ]:
import numpy as np
A = np.array([[1, 2],
              [3, 4]])
b = np.array([[5],
              [6]])
x = np.linalg.solve(A, b)
print(x)

[[-4. ]
 [ 4.5]]


### **Solving Linear Equations using Least Square method**

In [ ]:
import numpy as np
A = np.array([[1, 2],
              [3, 4],
              [7, 8]])
b = np.array([[5],
              [6],
              [9]])
x = np.linalg.lstsq(A, b, rcond=None)[0]
print(x)

[[-3.5       ]
 [ 4.17857143]]
