<a href="https://colab.research.google.com/github/sreeyadora/college/blob/main/ridge_and_lasso_with_evaluation_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score



In [2]:
df = pd.read_csv('bouston_housing_pricing.csv')
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values
print(x)
print(y)



[[  0  18   2 ...  15 397   5]
 [  0   0   7 ...  18 397   9]
 [  0   0   7 ...  18 393   4]
 ...
 [  9   0  18 ...  20 392  17]
 [  6   0  18 ...  20 397  19]
 [  8   0  18 ...  20 393  20]]
[24 22 35 33 36 29 23 27 17 19 15 19 22 20 18 20 23 18 20 18 14 20 15 15
 16 14 17 15 18 21 13 15 13 13 14 19 20 21 25 31 35 27 25 25 21 19 20 17
 14 19 20 21 25 23 19 35 25 32 23 20 19 16 22 25 33 24 19 22 17 21 24 22
 23 23 24 21 20 21 21 20 28 24 25 23 24 27 23 22 24 29 23 22 23 25 21 28
 21 39 44 33 28 27 19 19 20 20 20 20 20 19 22 23 19 19 19 18 21 19 20 19
 22 20 21 17 19 21 16 16 18 14 19 20 23 18 16 18 17 17 13 18 14 14 13 16
 12 14 16 15 18 15 22 20 15 19 17 16 13 41 24 23 27 50 50 50 23 25 50 24
 24 22 17 19 23 24 23 29 23 25 30 37 40 36 38 33 26 30 50 32 30 35 37 31
 36 31 29 50 33 30 35 35 33 24 42 49 50 23 24 23 24 20 22 19 22 28 24 25
 23 29 22 23 27 22 28 30 45 50 38 32 47 32 24 32 42 48 29 24 25 32 24 23
 22 20 22 24 18 19 24 21 25 26 24 25 30 43 22 21 44 50 36 30 34 43 49 31
 37 2

In [3]:
ct = ColumnTransformer(transformers=[('encoding',OneHotEncoder(),[3])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
print(x)


[[  1.   0.   0. ...  15. 397.   5.]
 [  1.   0.   0. ...  18. 397.   9.]
 [  1.   0.   0. ...  18. 393.   4.]
 ...
 [  1.   0.   9. ...  20. 392.  17.]
 [  1.   0.   6. ...  20. 397.  19.]
 [  1.   0.   8. ...  20. 393.  20.]]


In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, random_state=1)
print(x_train)
print(x_test)
print(y_train)
print(y_test)



[[  1.   0.   0. ...  20. 397.   6.]
 [  1.   0.   0. ...  20. 397.   9.]
 [  1.   0.   0. ...  19. 389.  14.]
 ...
 [  1.   0.   0. ...  19. 391.   6.]
 [  1.   0.   0. ...  17. 377.  11.]
 [  1.   0.   0. ...  19. 397.   9.]]
[[  1.   0.   0. ...  17. 393.  10.]
 [  1.   0.   4. ...  20. 391.  13.]
 [  1.   0.   0. ...  19. 396.   6.]
 ...
 [  1.   0.   2. ...  15. 348.  12.]
 [  1.   0.   0. ...  19. 397.   7.]
 [  1.   0.   0. ...  19. 376.  10.]]
[23 20 22 22 27 19 22 19  9 19 44 40 18 11 22 24 20 19 29 18 50 17 13 23
 21 19 19 25 23 33 24 20 30 22 19 24 25 22 23 50 22 13 14 50 25 27 32 23
 22 50 23 23 32 31 15 19 28 14 22 29 18 18 14 17 18 13 24 24 21 21 13 25
 20 31 22 20 13 24 17 24 33 23 19 50 18 15 35 32 13 35 14 20 44 23 13 29
 19 50 25 41 18 20 34 19 13 15 24 10 12 20 19 24 24 10 17 19 25 23 36 35
 20 27 23 21 23 35 32 17 16 25 32 26 23 16 22 21 22 20 17 17 32 29 25 24
 24 37 36 39 19 20 25 17 18 19 23 29 35 38 23 19 27 19 25 19 21 31 14 18
 42 15 25 15 21 21 22 22 32 28 20

In [12]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [5]:
y_pred = regressor.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))


[[24.27 23.  ]
 [22.64 23.  ]
 [23.45 24.  ]
 [35.78 32.  ]
 [43.13 50.  ]
 [37.41 42.  ]
 [22.47 19.  ]
 [31.11 25.  ]
 [33.01 35.  ]
 [16.5  20.  ]
 [26.28 50.  ]
 [30.97 28.  ]
 [40.04 43.  ]
 [23.08 22.  ]
 [30.31 24.  ]
 [33.48 37.  ]
 [25.04 29.  ]
 [22.64 21.  ]
 [25.45 23.  ]
 [33.12 33.  ]
 [25.35 24.  ]
 [36.18 48.  ]
 [17.12 18.  ]
 [23.17 21.  ]
 [21.18 16.  ]
 [18.4  19.  ]
 [21.49 18.  ]
 [21.03 24.  ]
 [28.95 36.  ]
 [ 6.92 10.  ]
 [ 8.32 11.  ]
 [21.63 23.  ]
 [19.87 21.  ]
 [39.39 50.  ]
 [30.83 29.  ]
 [29.57 27.  ]
 [24.6  30.  ]
 [30.24 28.  ]
 [20.84 13.  ]
 [20.7  23.  ]
 [22.82 23.  ]
 [29.82 25.  ]
 [20.   20.  ]
 [30.03 30.  ]
 [35.18 28.  ]
 [35.65 36.  ]
 [35.76 47.  ]
 [25.08 22.  ]
 [23.17 24.  ]
 [28.4  24.  ]
 [13.14 20.  ]
 [21.42 19.  ]
 [23.72 28.  ]
 [27.67 23.  ]
 [26.43 24.  ]
 [30.35 24.  ]
 [21.43 22.  ]
 [28.26 24.  ]
 [43.57 50.  ]
 [15.97 12.  ]
 [26.59 15.  ]
 [ 2.16  9.  ]
 [20.5  22.  ]
 [29.93 33.  ]
 [34.28 28.  ]
 [23.53 20.  ]
 [36.52 33

In [6]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))
print("r2 score",r2_score(y_test,y_pred))


MAE 3.6091263090563177
MSE 26.037356674774802
RMSE 5.102681322086928
r2 score 0.6938582401554991


In [7]:
from sklearn.linear_model import Ridge,Lasso  

In [8]:
ridgeR = Ridge(alpha = 1)
ridgeR.fit(x_train, y_train)
y_pred = ridgeR.predict(x_test)



In [9]:
print("MAE",mean_absolute_error(y_test,y_pred))
print("MSE",mean_squared_error(y_test,y_pred))
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))
print("r2 score",r2_score(y_test,y_pred))



MAE 3.611634854090215
MSE 26.05450204624847
RMSE 5.10436108110001
r2 score 0.6936566484862026


In [10]:
lasso = Lasso(alpha = 1)
lasso.fit(x_train, y_train)
y_pred1 = lasso.predict(x_test)


In [11]:
print("MAE",mean_absolute_error(y_test,y_pred1))
print("MSE",mean_squared_error(y_test,y_pred1))
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred1)))
print("r2 score",r2_score(y_test,y_pred1))


MAE 4.109588631224574
MSE 34.35663924820149
RMSE 5.861453680461997
r2 score 0.5960418665702354
